from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import StreamingResponse
from typing import List, Dict, Any, Optional
from datetime import datetime
import json
import io
import csv

from backend.security.dependencies import get_current_active_user
from backend.security.models import User

router = APIRouter(prefix="/reports", tags=["reports"])


# Mock data untuk laporan
MOCK_CASES = [
    {"id": "1", "title": "Fraud Investigation", "status": "investigating", "priority": "high", "created_at": "2026-06-01"},
    {"id": "2", "title": "Procurement Collusion", "status": "open", "priority": "critical", "created_at": "2026-05-28"},
    {"id": "3", "title": "Conflict of Interest", "status": "resolved", "priority": "high", "created_at": "2026-05-25"},
]

MOCK_EVENTS = [
    {"event_type": "case_created", "timestamp": "2026-06-01T10:00:00", "user": "admin"},
    {"event_type": "case_assigned", "timestamp": "2026-06-01T11:00:00", "user": "investigator"},
    {"event_type": "evidence_added", "timestamp": "2026-06-02T09:00:00", "user": "investigator"},
]

MOCK_ENTITIES = [
    {"name": "PT. Maju Jaya", "type": "vendor", "risk_score": 92},
    {"name": "CV. Karya Mandiri", "type": "vendor", "risk_score": 88},
    {"name": "Kementerian PUPR", "type": "institution", "risk_score": 65},
]


def generate_pdf_report(report_data: Dict) -> bytes:
    """Generate PDF report (mock - returns HTML for demo)"""
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>NEMESIS Intelligence Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #3498db; color: white; }}
            .header {{ text-align: center; margin-bottom: 30px; }}
            .footer {{ text-align: center; margin-top: 50px; font-size: 12px; color: #7f8c8d; }}
            .risk-high {{ color: #e74c3c; }}
            .risk-medium {{ color: #f39c12; }}
            .risk-low {{ color: #27ae60; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>NEMESIS V8+ Intelligence Report</h1>
            <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p>Report Type: {report_data.get('type', 'summary').upper()}</p>
        </div>
        
        <h2>Executive Summary</h2>
        <p>Total Cases: {len(MOCK_CASES)}</p>
        <p>Active Investigations: {len([c for c in MOCK_CASES if c['status'] in ['open', 'investigating']])}</p>
        <p>High Risk Entities: {len([e for e in MOCK_ENTITIES if e['risk_score'] >= 70])}</p>
        
        <h2>Cases Overview</h2>
        <table>
            <tr><th>ID</th><th>Title</th><th>Status</th><th>Priority</th><th>Created</th></tr>
            {''.join([f"<tr><td>{c['id']}</td><td>{c['title']}</td><td>{c['status']}</td><td class='risk-{c['priority']}'>{c['priority']}</td><td>{c['created_at']}</td></tr>" for c in MOCK_CASES])}
        </table>
        
        <h2>High Risk Entities</h2>
        <table>
            <tr><th>Entity</th><th>Type</th><th>Risk Score</th></tr>
            {''.join([f"<tr><td>{e['name']}</td><td>{e['type']}</td><td class='risk-{'high' if e['risk_score'] >= 70 else 'medium' if e['risk_score'] >= 50 else 'low'}'>{e['risk_score']}%</td></tr>" for e in MOCK_ENTITIES])}
        </table>
        
        <h2>Recent Events</h2>
        <table>
            <tr><th>Event Type</th><th>Timestamp</th><th>User</th></tr>
            {''.join([f"<tr><td>{e['event_type']}</td><td>{e['timestamp']}</td><td>{e['user']}</td></tr>" for e in MOCK_EVENTS])}
        </table>
        
        <div class="footer">
            <p>This report is generated by NEMESIS V8+ Intelligence Platform</p>
            <p>© 2026 - All Rights Reserved</p>
        </div>
    </body>
    </html>
    """
    return html_content.encode('utf-8')


def generate_json_report(report_data: Dict) -> str:
    """Generate JSON report"""
    output = {
        "report_id": datetime.now().strftime("%Y%m%d%H%M%S"),
        "generated_at": datetime.now().isoformat(),
        "type": report_data.get('type', 'summary'),
        "summary": {
            "total_cases": len(MOCK_CASES),
            "active_cases": len([c for c in MOCK_CASES if c['status'] in ['open', 'investigating']]),
            "high_risk_entities": len([e for e in MOCK_ENTITIES if e['risk_score'] >= 70]),
            "total_events": len(MOCK_EVENTS)
        },
        "cases": MOCK_CASES,
        "entities": MOCK_ENTITIES,
        "events": MOCK_EVENTS
    }
    return json.dumps(output, indent=2)


def generate_csv_report(report_data: Dict) -> str:
    """Generate CSV report"""
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Cases
    writer.writerow(['=== CASES ==='])
    writer.writerow(['ID', 'Title', 'Status', 'Priority', 'Created At'])
    for case in MOCK_CASES:
        writer.writerow([case['id'], case['title'], case['status'], case['priority'], case['created_at']])
    
    writer.writerow([])
    writer.writerow(['=== HIGH RISK ENTITIES ==='])
    writer.writerow(['Name', 'Type', 'Risk Score'])
    for entity in MOCK_ENTITIES:
        writer.writerow([entity['name'], entity['type'], f"{entity['risk_score']}%"])
    
    writer.writerow([])
    writer.writerow(['=== RECENT EVENTS ==='])
    writer.writerow(['Event Type', 'Timestamp', 'User'])
    for event in MOCK_EVENTS:
        writer.writerow([event['event_type'], event['timestamp'], event['user']])
    
    return output.getvalue()


@router.post("/generate")
async def generate_report(
    report_data: Dict[str, Any],
    current_user: User = Depends(get_current_active_user)
):
    """Generate report in specified format"""
    report_type = report_data.get('type', 'summary')
    format_type = report_data.get('format', 'pdf')
    
    if format_type == 'pdf':
        content = generate_pdf_report(report_data)
        media_type = 'application/pdf'
        filename = f"nemesis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    elif format_type == 'json':
        content = generate_json_report(report_data)
        media_type = 'application/json'
        filename = f"nemesis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    elif format_type == 'csv':
        content = generate_csv_report(report_data)
        media_type = 'text/csv'
        filename = f"nemesis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    else:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {format_type}")
    
    return Response(
        content=content,
        media_type=media_type,
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@router.get("/templates/{template_name}")
async def get_report_template(
    template_name: str,
    current_user: User = Depends(get_current_active_user)
):
    """Get report template for download"""
    templates = {
        "vendors": {
            "name": "vendor_template.xlsx",
            "content": "Name,Registration Number,Tax ID,Address,City,Business Type\nPT. Contoh,1234567890,01.234.567.8-901.000,Jl. Contoh No. 1,Jakarta,Kontraktor"
        },
        "cases": {
            "name": "case_template.xlsx",
            "content": "Title,Description,Priority,Status\nContoh Kasus,Deskripsi kasus,HIGH,OPEN"
        },
        "evidence": {
            "name": "evidence_template.xlsx",
            "content": "Title,Description,Type,Case ID\nContoh Bukti,Deskripsi bukti,document,CASE-001"
        }
    }
    
    if template_name not in templates:
        raise HTTPException(status_code=404, detail=f"Template {template_name} not found")
    
    template = templates[template_name]
    return Response(
        content=template["content"],
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={template['name']}"}
    )


@router.get("/history")
async def get_report_history(
    limit: int = 50,
    offset: int = 0,
    current_user: User = Depends(get_current_active_user)
):
    """Get report generation history"""
    mock_history = [
        {"id": "1", "name": "Q2 2026 Fraud Analysis", "date": "2026-06-01", "type": "summary", "status": "completed"},
        {"id": "2", "name": "Vendor Collusion Investigation", "date": "2026-05-28", "type": "detailed", "status": "completed"},
        {"id": "3", "name": "Hash Chain Integrity Report", "date": "2026-05-25", "type": "forensic", "status": "completed"},
    ]
    
    total = len(mock_history)
    history = mock_history[offset:offset + limit]
    
    return {"data": history, "total": total, "offset": offset, "limit": limit}
