import json

from sqlalchemy import text


class FindingLifecycleService:
    """
    Handles immutable lifecycle events for findings.

    Transaction Policy
    ------------------
    - This service NEVER performs commit() or rollback().
    - Transaction ownership belongs to the caller.
    - Caller is responsible for:
        * commit()
        * rollback()
        * cache invalidation
    """

    def __init__(self, db):
        self.db = db

    async def record_event(
        self,
        finding_id: str,
        event: str,
        old_status: str | None = None,
        new_status: str |None = None,
        actor: str = "system",
        notes: str | None = None,
        metadata: dict | None = None,
    ):
        """
        Insert immutable lifecycle event.

        Does NOT commit.
        """

        await self.db.execute(
            text(
                """
                INSERT INTO finding_events
                (
                    finding_id,
                    event,
                    old_status,
                    new_status,
                    actor,
                    notes,
                    metadata
                )
                VALUES
                (
                    :finding_id,
                    :event,
                    :old_status,
                    :new_status,
                    :actor,
                    :notes,
                    CAST(:metadata AS json)
                )
                """
            ),
            {
                "finding_id": finding_id,
                "event": event,
                "old_status": old_status,
                "new_status": new_status,
                "actor": actor,
                "notes": notes,
                "metadata": (
                    json.dumps(metadata)
                    if metadata is not None
                    else None
                ),
            },
        )

    async def ensure_created_event(
        self,
        finding_id: str,
        actor: str = "system",
        notes: str | None = None,
    ) -> bool:
        """
        Ensure CREATED event exists for a finding.
        Returns True if event was created, False if already existed.
        """
        event_exists = await self.db.execute(
            text("""
                SELECT 1
                FROM finding_events
                WHERE finding_id=:finding_id
                AND event='CREATED'
                LIMIT 1
            """),
            {"finding_id": finding_id}
        )

        if event_exists.fetchone():
            return False  # Already exists

        await self.record_event(
            finding_id=finding_id,
            event="CREATED",
            new_status="UNDER_REVIEW",
            actor=actor,
            notes=notes or "Finding generated by intelligence engine",
            metadata={
                "source": "finding_lifecycle",
                "created_by": actor
            }
        )
        return True  # Newly created


    async def get_history(
        self,
        finding_id: str,
    ):
        """
        Read-only lifecycle history.

        No UPDATE.
        No COMMIT.
        """

        result = await self.db.execute(
            text(
                """
                SELECT
                    id,
                    event,
                    old_status,
                    new_status,
                    actor,
                    notes,
                    metadata,
                    created_at
                FROM finding_events
                WHERE finding_id = :finding_id
                ORDER BY created_at ASC
                """
            ),
            {
                "finding_id": finding_id,
            },
        )

        return [
            dict(row)
            for row in result.mappings()
        ]


    async def transition(
        self,
        finding_id: str,
        new_status: str,
        actor: str,
        notes: str | None = None,
    ):
        """
        Transition finding status.

        Performs:
            SELECT
            UPDATE
            INSERT EVENT

        Does NOT commit.

        Returns metadata so caller can
        commit then invalidate cache.
        """

        from backend.services.finding_state_machine import (
            FindingStateMachine,
        )

        result = await self.db.execute(
            text(
                """
                SELECT status
                FROM findings
                WHERE id = :finding_id
                """
            ),
            {
                "finding_id": finding_id,
            },
        )

        row = result.fetchone()

        if not row:
            raise Exception("Finding not found")

        old_status = row.status

        if not FindingStateMachine.can_transition(
            old_status,
            new_status,
        ):
            raise Exception(
                f"Invalid transition "
                f"{old_status} -> {new_status}"
            )

        await self.db.execute(
            text(
                """
                UPDATE findings
                SET
                    status = :new_status,
                    updated_at = NOW()
                WHERE id = :finding_id
                """
            ),
            {
                "finding_id": finding_id,
                "new_status": new_status,
            },
        )

        await self.record_event(
            finding_id=finding_id,
            event="STATUS_CHANGED",
            old_status=old_status,
            new_status=new_status,
            actor=actor,
            notes=notes,
            metadata={
                "transition": {
                    "from": old_status,
                    "to": new_status,
                },
                "source": "finding_lifecycle",
            },
        )

        return {
            "finding_id": finding_id,
            "old_status": old_status,
            "new_status": new_status,
            "cache_invalidation_required": True,
        }