# backend/events/registry.py
from enum import Enum
from typing import Dict, Type, Any, Optional
from pydantic import BaseModel
from .base import BaseEvent

class AggregateType(str, Enum):
    CASE = "CASE"
    EVIDENCE = "EVIDENCE"
    ENTITY = "ENTITY"
    FINDING = "FINDING"
    RECOMMENDATION = "RECOMMENDATION"
    OUTCOME = "OUTCOME"
    RECOVERY = "RECOVERY"
    USER = "USER"
    RELATIONSHIP = "RELATIONSHIP"
    DATA_LINEAGE = "DATA_LINEAGE"
    MODEL = "MODEL"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    FOLLOWUP = "FOLLOWUP"
    CUSTODY = "CUSTODY"
    THREAD = "THREAD"
    DATA_SOURCE = "DATA_SOURCE"


class EventType(str, Enum):
    # CASE Events (20)
    CASE_REPORTED = "CASE_REPORTED"
    CASE_SCREENED = "CASE_SCREENED"
    CASE_ASSESSED = "CASE_ASSESSED"
    CASE_INVESTIGATION_STARTED = "CASE_INVESTIGATION_STARTED"
    CASE_FINDING_RECORDED = "CASE_FINDING_RECORDED"
    CASE_RECOMMENDATION_ISSUED = "CASE_RECOMMENDATION_ISSUED"
    CASE_FOLLOWUP_STARTED = "CASE_FOLLOWUP_STARTED"
    CASE_CLOSED = "CASE_CLOSED"
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    CASE_STATUS_CHANGED = "CASE_STATUS_CHANGED"
    CASE_PRIORITY_CHANGED = "CASE_PRIORITY_CHANGED"
    CASE_ASSIGNED = "CASE_ASSIGNED"
    CASE_REASSIGNED = "CASE_REASSIGNED"
    CASE_UNASSIGNED = "CASE_UNASSIGNED"
    CASE_APPROVED = "CASE_APPROVED"
    CASE_REJECTED = "CASE_REJECTED"
    CASE_ESCALATED_TO_APH = "CASE_ESCALATED_TO_APH"
    CASE_RISK_SCORE_UPDATED = "CASE_RISK_SCORE_UPDATED"
    CASE_TRUST_SCORE_UPDATED = "CASE_TRUST_SCORE_UPDATED"
    
    # EVIDENCE Events (10)
    EVIDENCE_ADDED = "EVIDENCE_ADDED"
    EVIDENCE_UPDATED = "EVIDENCE_UPDATED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    EVIDENCE_TRUST_SCORE_UPDATED = "EVIDENCE_TRUST_SCORE_UPDATED"
    EVIDENCE_ARCHIVED = "EVIDENCE_ARCHIVED"
    EVIDENCE_DELETED = "EVIDENCE_DELETED"
    EVIDENCE_HASH_VALIDATED = "EVIDENCE_HASH_VALIDATED"
    EVIDENCE_HASH_MISMATCH = "EVIDENCE_HASH_MISMATCH"
    EVIDENCE_CHAIN_VERIFIED = "EVIDENCE_CHAIN_VERIFIED"
    EVIDENCE_CHAIN_BROKEN = "EVIDENCE_CHAIN_BROKEN"
    
    # ENTITY Events (5)
    ENTITY_CREATED = "ENTITY_CREATED"
    ENTITY_UPDATED = "ENTITY_UPDATED"
    ENTITY_MERGED = "ENTITY_MERGED"
    ENTITY_RISK_SCORE_UPDATED = "ENTITY_RISK_SCORE_UPDATED"
    ENTITY_BLACKLISTED = "ENTITY_BLACKLISTED"
    
    # FINDING Events (6)
    FINDING_CREATED = "FINDING_CREATED"
    FINDING_UPDATED = "FINDING_UPDATED"
    FINDING_APPROVED = "FINDING_APPROVED"
    FINDING_REJECTED = "FINDING_REJECTED"
    FINDING_EVIDENCE_LINKED = "FINDING_EVIDENCE_LINKED"
    FINDING_EVIDENCE_UNLINKED = "FINDING_EVIDENCE_UNLINKED"
    
    # RECOMMENDATION Events (5)
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    RECOMMENDATION_UPDATED = "RECOMMENDATION_UPDATED"
    RECOMMENDATION_APPROVED = "RECOMMENDATION_APPROVED"
    RECOMMENDATION_REJECTED = "RECOMMENDATION_REJECTED"
    RECOMMENDATION_STATUS_CHANGED = "RECOMMENDATION_STATUS_CHANGED"
    
    # OUTCOME Events (2)
    OUTCOME_CREATED = "OUTCOME_CREATED"
    OUTCOME_UPDATED = "OUTCOME_UPDATED"
    
    # RECOVERY Events (3)
    RECOVERY_TARGET_SET = "RECOVERY_TARGET_SET"
    RECOVERY_ACTION_RECORDED = "RECOVERY_ACTION_RECORDED"
    RECOVERY_TARGET_ACHIEVED = "RECOVERY_TARGET_ACHIEVED"
    
    # USER Events (5)
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    
    # SECURITY Events (5)
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    ACCESS_DENIED = "ACCESS_DENIED"
    PERMISSION_GRANTED = "PERMISSION_GRANTED"
    PERMISSION_REVOKED = "PERMISSION_REVOKED"
    
    # RELATIONSHIP Events (6)
    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    RELATIONSHIP_DISCOVERED = "RELATIONSHIP_DISCOVERED"
    RELATIONSHIP_VERIFIED = "RELATIONSHIP_VERIFIED"
    RELATIONSHIP_REJECTED = "RELATIONSHIP_REJECTED"
    RELATIONSHIP_UPDATED = "RELATIONSHIP_UPDATED"
    RELATIONSHIP_CONFIDENCE_UPDATED = "RELATIONSHIP_CONFIDENCE_UPDATED"
    
    # DATA LINEAGE Events (4)
    DATA_IMPORTED = "DATA_IMPORTED"
    DATA_TRANSFORMED = "DATA_TRANSFORMED"
    DATA_VALIDATED = "DATA_VALIDATED"
    DATA_REJECTED = "DATA_REJECTED"
    
    # MODEL Events (4)
    MODEL_REGISTERED = "MODEL_REGISTERED"
    MODEL_VALIDATED = "MODEL_VALIDATED"
    MODEL_DEPLOYED = "MODEL_DEPLOYED"
    MODEL_RETIRED = "MODEL_RETIRED"
    
    # Others (remaining events)
    RISK_ASSESSMENT_CREATED = "RISK_ASSESSMENT_CREATED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    FOLLOWUP_STATUS_CHANGED = "FOLLOWUP_STATUS_CHANGED"
    FOLLOWUP_EVIDENCE_LINKED = "FOLLOWUP_EVIDENCE_LINKED"
    CUSTODY_EVENT_CREATED = "CUSTODY_EVENT_CREATED"
    THREAD_CREATED = "THREAD_CREATED"
    DATA_SOURCE_CREATED = "DATA_SOURCE_CREATED"
    DATA_SOURCE_UPDATED = "DATA_SOURCE_UPDATED"
    DATA_SOURCE_SYNCED = "DATA_SOURCE_SYNCED"


# Event Schema Registry
_event_schemas: Dict[EventType, Type[BaseEvent]] = {}

def register_event_schema(event_type: EventType, schema_class: Type[BaseEvent]):
    """Register event schema untuk validasi"""
    _event_schemas[event_type] = schema_class

def get_event_schema(event_type: EventType) -> Optional[Type[BaseEvent]]:
    """Get event schema berdasarkan event type"""
    return _event_schemas.get(event_type)

def get_all_event_schemas() -> Dict[EventType, Type[BaseEvent]]:
    """Get all registered event schemas"""
    return _event_schemas.copy()