FROM python:3.14-slim

WORKDIR /app

RUN pip install fastapi uvicorn sqlalchemy asyncpg psycopg2-binary pydantic python-multipart prometheus-client

COPY ./backend /app/backend

EXPOSE 8000

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
