from fastapi import APIRouter, Depends, HTTPException
from typing import List, Dict, Any
from datetime import datetime
import uuid

from backend.security.dependencies import get_current_active_user
from backend.security.models import User

router = APIRouter(prefix="/alerts", tags=["alerts"])

# Simple in-memory storage
alerts_db = []


@router.get("/")
async def get_alerts(
    limit: int = 50,
    offset: int = 0,
    current_user: User = Depends(get_current_active_user)
):
    """Get alerts list"""
    return alerts_db[offset:offset+limit] if alerts_db else []


@router.get("/summary/stats")
async def get_alert_stats(
    current_user: User = Depends(get_current_active_user)
):
    """Get alert statistics"""
    total = len(alerts_db)
    critical = len([a for a in alerts_db if a.get("severity") == "critical"])
    return {
        "total": total,
        "unresolved_critical": critical,
        "by_status": {"new": total, "acknowledged": 0, "resolved": 0}
    }


@router.post("/test")
async def test_alert(
    current_user: User = Depends(get_current_active_user)
):
    """Generate test alert"""
    alert = {
        "id": str(uuid.uuid4()),
        "title": "Test System Alert",
        "description": "This is a test alert generated by the system",
        "severity": "info",
        "status": "new",
        "timestamp": datetime.now().isoformat(),
        "source": "test",
        "user": current_user.username
    }
    alerts_db.append(alert)
    return {"message": "Test alert sent", "alert_id": alert["id"]}


@router.post("/{alert_id}/acknowledge")
async def acknowledge_alert(
    alert_id: str,
    current_user: User = Depends(get_current_active_user)
):
    """Acknowledge an alert"""
    for alert in alerts_db:
        if alert["id"] == alert_id:
            alert["status"] = "acknowledged"
            return {"status": "acknowledged", "alert_id": alert_id}
    raise HTTPException(status_code=404, detail="Alert not found")


@router.post("/{alert_id}/resolve")
async def resolve_alert(
    alert_id: str,
    current_user: User = Depends(get_current_active_user)
):
    """Resolve an alert"""
    for alert in alerts_db:
        if alert["id"] == alert_id:
            alert["status"] = "resolved"
            return {"status": "resolved", "alert_id": alert_id}
    raise HTTPException(status_code=404, detail="Alert not found")
