"""
Repository Generator — Generate repository from schema report.

Mengurangi boilerplate 70-80%.
"""

import json
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template


class RepositoryGenerator:
    """
    Repository Generator — Generate repository dari schema_report.json.
    
    Output:
        - backend/repositories/generated/fraud_repository.py
        - backend/repositories/generated/risk_repository.py
        - ...
    """
    
    REPOSITORY_TEMPLATE = '''
"""
{{ table_name }} Repository — Generated from Schema Audit.

Generated by repository_generator.py
Do not edit manually.
"""

from uuid import UUID
from typing import Sequence
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.exc import SQLAlchemyError

from backend.repositories.interfaces.{{ interface_name }} import I{{ interface_name }}
from backend.repositories.rows.{{ row_name }} import {{ row_name }}Row
from backend.infrastructure.sql_repository import SQLRepository
from backend.infrastructure.exceptions import SQLExecutionError
from backend.infrastructure.unit_of_work import IUnitOfWork


class {{ class_name }}(I{{ interface_name }}):
    """
    {{ table_name }} Repository.
    
    Schema Info:
        - Table: {{ table_name }}
        - Columns: {{ columns|join(", ") }}
        - PK: {{ primary_key }}
    """
    
    def __init__(self, sql_repo: SQLRepository):
        self._sql_repo = sql_repo
    
    async def get_summary(self, uow: IUnitOfWork, case_id: UUID) -> {{ row_name }}Row:
        """
        Get {{ table_name }} summary.
        """
        try:
            sql = self._sql_repo.load("{{ collector_name }}", "summary")
            
            result = await uow.session.execute(
                text(sql),
                {"case_id": case_id}
            )
            row = result.mappings().first()
            
            if not row:
                return {{ row_name }}Row.empty()
            
            return {{ row_name }}Row(
                {% for col in summary_columns %}
                {{ col.name }}=row.get("{{ col.name }}", {{ col.default }}),
                {% endfor %}
            )
        except SQLAlchemyError as e:
            raise SQLExecutionError(
                f"Failed to get {{ table_name }} summary for case {case_id}: {e}",
                original_error=e
            )
'''
    
    def __init__(self, schema_report: Dict):
        self._schema_report = schema_report
        self._output_dir = Path("backend/repositories/generated")
    
    def generate(self):
        """Generate all repositories."""
        self._output_dir.mkdir(parents=True, exist_ok=True)
        
        for table_name, table_info in self._schema_report["tables"].items():
            if self._is_dashboard_table(table_name):
                self._generate_repository(table_name, table_info)
    
    def _is_dashboard_table(self, table_name: str) -> bool:
        """Check if table is part of dashboard intelligence."""
        dashboard_tables = ["pattern_detections", "risk_scores", "graph_entities", 
                           "graph_relationships", "evidence", "rup_paket_detailed"]
        return table_name in dashboard_tables
    
    def _generate_repository(self, table_name: str, table_info: Dict):
        """Generate repository for one table."""
        collector_name = self._get_collector_name(table_name)
        interface_name = collector_name.capitalize()
        class_name = f"{collector_name.capitalize()}RepositoryImpl"
        row_name = f"{collector_name.capitalize()}Summary"
        
        # Determine columns for summary
        summary_columns = self._get_summary_columns(table_info)
        primary_key = table_info["primary_key"].get("constrained_columns", [])
        
        template = Template(self.REPOSITORY_TEMPLATE)
        content = template.render(
            table_name=table_name,
            collector_name=collector_name,
            interface_name=interface_name,
            class_name=class_name,
            row_name=row_name,
            columns=[c["name"] for c in table_info["columns"]],
            primary_key=primary_key,
            summary_columns=summary_columns,
        )
        
        output_path = self._output_dir / f"{collector_name}_repository.py"
        with open(output_path, "w") as f:
            f.write(content)
        print(f"Generated: {output_path}")
    
    def _get_collector_name(self, table_name: str) -> str:
        """Map table name to collector name."""
        mapping = {
            "pattern_detections": "fraud",
            "risk_scores": "risk",
            "graph_entities": "graph",
            "graph_relationships": "graph",
            "evidence": "evidence",
            "rup_paket_detailed": "procurement",
        }
        return mapping.get(table_name, table_name)
    
    def _get_summary_columns(self, table_info: Dict) -> List[Dict]:
        """Get columns for summary row."""
        # Hanya kolom yang relevan untuk summary
        exclude = ["id", "created_at", "updated_at"]
        return [
            {"name": c["name"], "default": "0" if c["type"] in ("integer", "numeric") else "None"}
            for c in table_info["columns"]
            if c["name"] not in exclude
        ]