apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nemesis-policy
  namespace: nemesis
spec:
  podSelector:
    matchLabels:
      app: nemesis
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nginx-ingress
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: database
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: redis
    ports:
    - protocol: TCP
      port: 6379