apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nemesis
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'nemesis-api'
      static_configs:
      - targets: ['nemesis-api:8000']
      metrics_path: '/metrics'