"""check_outbox

Revision ID: 9714e914a58b
Revises: 6f87cd663a63
Create Date: 2026-08-04 19:02:38.152752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9714e914a58b'
down_revision: Union[str, None] = '6f87cd663a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_report_case_type'), table_name='intelligence_reports')
    op.drop_index(op.f('ix_intelligence_reports_case_id'), table_name='intelligence_reports')
    op.drop_table('intelligence_reports')
    op.drop_table('users')
    op.drop_index(op.f('idx_events_aggregate'), table_name='events')
    op.drop_index(op.f('idx_events_commit'), table_name='events')
    op.drop_index(op.f('idx_events_tenant'), table_name='events')
    op.drop_index(op.f('idx_events_tenant_created'), table_name='events')
    op.drop_index(op.f('idx_events_type'), table_name='events')
    op.drop_table('events')
    op.drop_table('custody')
    op.drop_table('graph_clusters')
    op.drop_table('model_metrics')
    op.drop_index(op.f('idx_snapshots_aggregate'), table_name='snapshots')
    op.drop_index(op.f('idx_snapshots_tenant'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('rup_paket')
    op.drop_table('dashboard_view')
    op.drop_index(op.f('idx_finding_events_finding_id'), table_name='finding_events')
    op.drop_table('finding_events')
    op.drop_index(op.f('idx_graph_metadata_case_id'), table_name='graph_metadata')
    op.drop_index(op.f('idx_graph_metadata_version'), table_name='graph_metadata')
    op.drop_table('graph_metadata')
    op.drop_index(op.f('idx_cases_latest_fraud'), table_name='cases', postgresql_using='gin')
    op.drop_index(op.f('idx_cases_latest_risk'), table_name='cases', postgresql_using='gin')
    op.drop_index(op.f('idx_cases_tenant_status'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('follow_up')
    op.drop_index(op.f('idx_timeline_case'), table_name='investigation_timeline')
    op.drop_index(op.f('idx_timeline_stage'), table_name='investigation_timeline')
    op.drop_table('investigation_timeline')
    op.drop_index(op.f('idx_action_logs_finding'), table_name='finding_action_logs')
    op.drop_index(op.f('idx_action_logs_type'), table_name='finding_action_logs')
    op.drop_table('finding_action_logs')
    op.drop_table('fraud_evidence')
    op.drop_table('finding_comments')
    op.drop_table('approvals')
    op.drop_index(op.f('idx_findings_fingerprint'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_pattern_detections_case_id'), table_name='pattern_detections')
    op.drop_table('pattern_detections')
    op.drop_index(op.f('idx_alert_case_status'), table_name='alerts')
    op.drop_index(op.f('idx_alert_severity_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('assignments')
    op.drop_table('graph_relationships')
    op.drop_table('recovery_actions')
    op.drop_table('historical_risk_data')
    op.drop_index(op.f('idx_assignment_sla_due'), table_name='finding_assignments')
    op.drop_index(op.f('idx_finding_assignment_finding'), table_name='finding_assignments')
    op.drop_index(op.f('uq_active_finding_assignment'), table_name='finding_assignments', postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.drop_table('finding_assignments')
    op.drop_table('graph_entities')
    op.drop_index(op.f('idx_risk_explanations_case'), table_name='risk_explanations')
    op.drop_table('risk_explanations')
    op.drop_table('graph_entity_metrics')
    op.drop_index(op.f('idx_review_decision_finding'), table_name='finding_review_decisions')
    op.drop_table('finding_review_decisions')
    op.drop_table('outcome')
    op.drop_table('collusion_detections')
    op.drop_index(op.f('idx_risk_case_score'), table_name='risk_scores')
    op.drop_index(op.f('idx_risk_entity'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_case_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_entity_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_table('audit_log')
    op.drop_index(op.f('idx_recommendations_finding'), table_name='investigation_recommendations')
    op.drop_table('investigation_recommendations')
    op.drop_table('graph_node_scores')
    op.drop_index(op.f('idx_findings_case'), table_name='investigation_findings')
    op.drop_table('investigation_findings')
    op.drop_index(op.f('idx_rup_detailed_instansi'), table_name='rup_paket_detailed')
    op.drop_index(op.f('idx_rup_detailed_kode_paket'), table_name='rup_paket_detailed')
    op.drop_index(op.f('idx_rup_detailed_penyedia'), table_name='rup_paket_detailed')
    op.drop_index(op.f('idx_rup_detailed_penyedia_tahun'), table_name='rup_paket_detailed')
    op.drop_index(op.f('idx_rup_detailed_tahun'), table_name='rup_paket_detailed')
    op.drop_table('rup_paket_detailed')
    op.drop_index(op.f('idx_evidence_files_case'), table_name='evidence_files')
    op.drop_index(op.f('idx_evidence_files_hash'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_projection_checkpoints_projection_name'), table_name='projection_checkpoints')
    op.drop_table('projection_checkpoints')
    op.drop_table('evidence')
    op.drop_index(op.f('idx_anomaly_case_type'), table_name='anomaly_detections')
    op.drop_index(op.f('idx_anomaly_severity'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_case_id'), table_name='anomaly_detections')
    op.drop_table('anomaly_detections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_detections',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detection_type', postgresql.ENUM('STATISTICAL', 'GRAPH', 'ML', 'RULE', 'TEMPORAL', name='detectiontype'), autoincrement=False, nullable=False),
    sa.Column('anomaly_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('observed_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expected_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('anomaly_detections_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('anomaly_detections_pkey'))
    )
    op.create_index(op.f('ix_anomaly_detections_case_id'), 'anomaly_detections', ['case_id'], unique=False)
    op.create_index(op.f('idx_anomaly_severity'), 'anomaly_detections', ['severity'], unique=False)
    op.create_index(op.f('idx_anomaly_case_type'), 'anomaly_detections', ['case_id', 'detection_type'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('trust_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_pkey'))
    )
    op.create_table('projection_checkpoints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('projection_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('projection_checkpoints_pkey'))
    )
    op.create_index(op.f('ix_projection_checkpoints_projection_name'), 'projection_checkpoints', ['projection_name'], unique=True)
    op.create_table('evidence_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sha256_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('sha512_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=127), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('integrity_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('evidence_files_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_files_pkey'))
    )
    op.create_index(op.f('idx_evidence_files_hash'), 'evidence_files', ['sha256_hash'], unique=False)
    op.create_index(op.f('idx_evidence_files_case'), 'evidence_files', ['case_id'], unique=False)
    op.create_table('rup_paket_detailed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kode_paket', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('kode_rup', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('tahun_anggaran', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nama_instansi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('satuan_kerja', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nama_penyedia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nama_paket', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_nilai', sa.NUMERIC(precision=20, scale=0), autoincrement=False, nullable=True),
    sa.Column('nilai_pdn', sa.NUMERIC(precision=20, scale=0), autoincrement=False, nullable=True),
    sa.Column('sumber_transaksi', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sumber_dana', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metode_pengadaan', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('jenis_pengadaan', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status_paket', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rup_paket_detailed_pkey'))
    )
    op.create_index(op.f('idx_rup_detailed_tahun'), 'rup_paket_detailed', ['tahun_anggaran'], unique=False)
    op.create_index(op.f('idx_rup_detailed_penyedia_tahun'), 'rup_paket_detailed', ['nama_penyedia', 'tahun_anggaran'], unique=False)
    op.create_index(op.f('idx_rup_detailed_penyedia'), 'rup_paket_detailed', ['nama_penyedia'], unique=False)
    op.create_index(op.f('idx_rup_detailed_kode_paket'), 'rup_paket_detailed', ['kode_paket'], unique=False)
    op.create_index(op.f('idx_rup_detailed_instansi'), 'rup_paket_detailed', ['nama_instansi'], unique=False)
    op.create_table('investigation_findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('finding_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('investigation_findings_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_findings_pkey'))
    )
    op.create_index(op.f('idx_findings_case'), 'investigation_findings', ['case_id'], unique=False)
    op.create_table('graph_node_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('pagerank', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('degree', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weighted_degree', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_node_scores_pkey')),
    sa.UniqueConstraint('entity_id', name=op.f('uq_entity_score'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('investigation_recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recommendation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_entity', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'MEDIUM'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['investigation_findings.id'], name=op.f('investigation_recommendations_finding_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_recommendations_pkey'))
    )
    op.create_index(op.f('idx_recommendations_finding'), 'investigation_recommendations', ['finding_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_level', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='risklevel'), autoincrement=False, nullable=False),
    sa.Column('anomaly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('collusion_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('financial_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temporal_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('calculated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('risk_scores_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_scores_pkey'))
    )
    op.create_index(op.f('ix_risk_scores_entity_id'), 'risk_scores', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_case_id'), 'risk_scores', ['case_id'], unique=False)
    op.create_index(op.f('idx_risk_entity'), 'risk_scores', ['entity_id', 'entity_type'], unique=False)
    op.create_index(op.f('idx_risk_case_score'), 'risk_scores', ['case_id', 'overall_score'], unique=False)
    op.create_table('collusion_detections',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('entity_names', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pattern_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_reviewed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('collusion_detections_pkey'))
    )
    op.create_table('outcome',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('estimated_loss', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('recovered_value', sa.NUMERIC(precision=20, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referred_to_aph', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('aph_institution', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('outcome_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('outcome_pkey'))
    )
    op.create_table('finding_review_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('decided_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('finding_review_decisions_pkey'))
    )
    op.create_index(op.f('idx_review_decision_finding'), 'finding_review_decisions', ['finding_id'], unique=False)
    op.create_table('graph_entity_metrics',
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('degree_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weighted_degree', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pagerank_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('betweenness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['graph_entities.id'], name=op.f('graph_entity_metrics_entity_id_fkey')),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('graph_entity_metrics_pkey'))
    )
    op.create_table('risk_explanations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('factor', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('contribution', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('risk_explanations_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_explanations_pkey'))
    )
    op.create_index(op.f('idx_risk_explanations_case'), 'risk_explanations', ['case_id'], unique=False)
    op.create_table('graph_entities',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_entities_pkey'))
    )
    op.create_table('finding_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('analyst_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('analyst_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sla_due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=50), server_default=sa.text("'NORMAL'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('finding_assignments_pkey'))
    )
    op.create_index(op.f('uq_active_finding_assignment'), 'finding_assignments', ['finding_id'], unique=True, postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.create_index(op.f('idx_finding_assignment_finding'), 'finding_assignments', ['finding_id'], unique=False)
    op.create_index(op.f('idx_assignment_sla_due'), 'finding_assignments', ['sla_due_at'], unique=False)
    op.create_table('historical_risk_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actual_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('predicted_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('prediction_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('historical_risk_data_pkey'))
    )
    op.create_table('recovery_actions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('outcome_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('recovery_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], name=op.f('recovery_actions_outcome_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recovery_actions_pkey'))
    )
    op.create_table('graph_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_relationships_pkey'))
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('assigned_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('assignments_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assignments_pkey'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('anomaly_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alertstatus'), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('triggered_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly_detections.id'], name=op.f('alerts_anomaly_id_fkey')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('alerts_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_index(op.f('idx_alert_severity_status'), 'alerts', ['severity', 'status'], unique=False)
    op.create_index(op.f('idx_alert_case_status'), 'alerts', ['case_id', 'status'], unique=False)
    op.create_table('pattern_detections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_validated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pattern_detections_pkey'))
    )
    op.create_index(op.f('ix_pattern_detections_case_id'), 'pattern_detections', ['case_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('projection_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_sequence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_events_pkey')),
    sa.UniqueConstraint('event_id', 'projection_name', name=op.f('uq_processed_event'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('findings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('finding_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED', name='findingstatus'), autoincrement=False, nullable=True),
    sa.Column('evidence_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('anomaly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('financial_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('escalated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('escalated_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detection_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('anomaly_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('findings_pkey')),
    sa.UniqueConstraint('case_id', 'finding_type', 'detection_method', 'fingerprint', name=op.f('uq_findings_case_type_method_fp'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_findings_fingerprint'), 'findings', ['fingerprint'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approval_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('approvals_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approvals_pkey'))
    )
    op.create_table('finding_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('finding_comments_pkey'))
    )
    op.create_table('fraud_evidence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('evidence_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fraud_evidence_pkey'))
    )
    op.create_table('finding_action_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('actor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('actor_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('finding_action_logs_pkey'))
    )
    op.create_index(op.f('idx_action_logs_type'), 'finding_action_logs', ['action_type'], unique=False)
    op.create_index(op.f('idx_action_logs_finding'), 'finding_action_logs', ['finding_id'], unique=False)
    op.create_table('investigation_timeline',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('from_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('investigation_timeline_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('investigation_timeline_pkey'))
    )
    op.create_index(op.f('idx_timeline_stage'), 'investigation_timeline', ['stage'], unique=False)
    op.create_index(op.f('idx_timeline_case'), 'investigation_timeline', ['case_id'], unique=False)
    op.create_table('follow_up',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recommendation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_taken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('follow_up_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('follow_up_pkey'))
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=50), server_default=sa.text("'MEDIUM'::character varying"), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('institution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), server_default=sa.text("'LOW'::character varying"), autoincrement=False, nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('workflow_stage', sa.VARCHAR(length=50), server_default=sa.text("'REPORTED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('investigation_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('investigation_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('review_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('review_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('latest_fraud', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_risk', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_graph', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_procurement', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint('version >= 0', name=op.f('ck_cases_version_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('cases_pkey'))
    )
    op.create_index(op.f('idx_cases_tenant_status'), 'cases', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('idx_cases_latest_risk'), 'cases', ['latest_risk'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_cases_latest_fraud'), 'cases', ['latest_fraud'], unique=False, postgresql_using='gin')
    op.create_table('graph_metadata',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regenerated_by', sa.VARCHAR(), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_metadata_pkey'))
    )
    op.create_index(op.f('idx_graph_metadata_version'), 'graph_metadata', ['version'], unique=False)
    op.create_index(op.f('idx_graph_metadata_case_id'), 'graph_metadata', ['case_id'], unique=False)
    op.create_table('finding_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_status', postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED', name='findingstatus'), autoincrement=False, nullable=True),
    sa.Column('new_status', postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED', name='findingstatus'), autoincrement=False, nullable=True),
    sa.Column('actor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('finding_events_pkey'))
    )
    op.create_index(op.f('idx_finding_events_finding_id'), 'finding_events', ['finding_id'], unique=False)
    op.create_table('dashboard_view',
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fraud_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('analysis_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evidence_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_events', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latest_fraud', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_risk', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_graph', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latest_procurement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('case_id', name=op.f('dashboard_view_pkey'))
    )
    op.create_table('rup_paket',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nomor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nama_paket', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pagu', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('jenis', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tahun', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('metode', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bulan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lokasi', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('instansi', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('hash_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rup_paket_pkey'))
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregate_type', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    sa.Column('snapshot_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('snapshots_pkey'))
    )
    op.create_index(op.f('idx_snapshots_tenant'), 'snapshots', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_snapshots_aggregate'), 'snapshots', ['aggregate_id', 'snapshot_version'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('precision', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('recall', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('f1_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('trained_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('training_data_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('model_metrics_pkey'))
    )
    op.create_table('graph_clusters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_clusters_pkey'))
    )
    op.create_table('custody',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('custody_pkey'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregate_type', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    sa.Column('event_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('event_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('aggregate_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('previous_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event_signature', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('signing_key_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('commit_position', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey')),
    sa.UniqueConstraint('commit_position', name=op.f('events_commit_position_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_events_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('idx_events_tenant_created'), 'events', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_events_tenant'), 'events', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_events_commit'), 'events', ['commit_position'], unique=False)
    op.create_index(op.f('idx_events_aggregate'), 'events', ['aggregate_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('intelligence_reports',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('shared_with', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('intelligence_reports_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('intelligence_reports_pkey'))
    )
    op.create_index(op.f('ix_intelligence_reports_case_id'), 'intelligence_reports', ['case_id'], unique=False)
    op.create_index(op.f('idx_report_case_type'), 'intelligence_reports', ['case_id', 'report_type'], unique=False)
    # ### end Alembic commands ###
