"""add_active_persistence_tables

Revision ID: f67a6e3b3b9e
Revises: 6f87cd663a63
Create Date: 2026-08-06 17:36:44.073074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67a6e3b3b9e'
down_revision: Union[str, None] = '6f87cd663a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_of_custody',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('case_id', sa.UUID(), nullable=False),
        sa.Column('evidence_id', sa.VARCHAR(), nullable=False),
        sa.Column('custodian', sa.VARCHAR(), nullable=False),
        sa.Column('status', sa.VARCHAR(), nullable=True),
        sa.Column('received_at', sa.DateTime(), nullable=True),
        sa.Column('transferred_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    )
    op.create_table('outbox_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
        sa.Column('aggregate_id', sa.UUID(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('status', sa.VARCHAR(length=50), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('last_error', sa.VARCHAR(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id'),
        sa.Index('idx_outbox_pending', 'status', 'created_at'),
        sa.Index('idx_outbox_aggregate', 'aggregate_id', 'event_type'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_messages')
    op.drop_table('chain_of_custody')
    # ### end Alembic commands ###