apiVersion: v1
kind: Service
metadata:
  name: nemesis-api-lb
  namespace: nemesis
spec:
  type: LoadBalancer
  selector:
    app: nemesis-api
  ports:
  - port: 80
    targetPort: 8000
    name: http
  - port: 443
    targetPort: 8000
    name: https
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800