"""verify_no_changes

revision = "04a7600b53fa"
down_revision = "f5ce90326d99"
branch_labels = None
depends_on = None
Create Date: 2026-06-14 10:35:46.712072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a7600b53fa'
down_revision: Union[str, None] = 'f5ce90326d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
